default_stages: [commit, push]

repos:
  # ---- BLACK (formatter) ----
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  # ---- RUFF (lint + format) ----
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # ---- MYPY (type-checking) ----
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        additional_dependencies: ["types-requests"]
        stages: [manual]

  # ---- NBSTRIPOUT (clean notebooks) ----
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout